version: "3.0"
services:
  influxdb:
    image: influxdb:1.8
    restart: always
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: energy
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: energy
      INFLUXDB_USER_PASSWORD: energy
    volumes:
      - influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000    
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  influxdb:
  grafana-storage:
