version: "3.0"
services:
  influxdb:
    image: influxdb:2.5
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin
      DOCKER_INFLUXDB_INIT_ORG: admin
      DOCKER_INFLUXDB_INIT_BUCKET: db0
    volumes:
      - inbfluxdb2:/var/lib/influxdb2
    
